//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppPP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KochnevPPLogistickEntities : DbContext
    {
        public KochnevPPLogistickEntities()
            : base("name=KochnevPPLogistickEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginTab> LoginTab { get; set; }
        public virtual DbSet<RecordOfInformation> RecordOfInformation { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
